#!/usr/bin/env sh
SCRIPT_PATH=`dirname "$0"`; SCRIPT_PATH=`eval "cd \"$SCRIPT_PATH\" && pwd"`

RST=''
RED=''
GRN=''
YEL=''
if [ -t 1 ] ; then
    RST='\033[0m'
    RED='\033[0;31m'
    GRN='\033[0;32m'
    YEL='\033[0;33m'
fi

success=0
total=0
for file in $SCRIPT_PATH/Test*.phi; do
    ((total=total+1))
    BASENAME=$(basename $file)
    DIRNAME=$(dirname $file)
    echo "Testing ${BASENAME}…"
    (cd $DIRNAME && "$SCRIPT_PATH/../phic" $file)
    exit="$?"
    if [ "$exit" != "0" ]; then
        echo "${RED}Regression in ${BASENAME}: Exit Code $exit${RST}"
    else
        iverilog -g2005-sv "${file}.sv" && echo "${GRN}$BASENAME output appears valid.${RST}" && ((success=success+1)) || echo "${YEL}IcarusVerilog has failed to process $BASENAME output.${RST}"
    fi
done

echo "Test results: $success/$total"
[ "$success" = "$total" ]
exit $?