/*
   Automatically generated by the Phi Compiler 0.0.1-dev (a8a7bc2)
   Do not modify.
   Generated on: 2018-10-28 18:20:16
*/

module dFlipFlop(
    input [64'd31:64'd0] a,
    output [64'd31:64'd0] b,
    input  clock,
    input reset
);

wire [64'd31:64'd0] v=x;
reg [64'd31:64'd0] store;
always @ (posedge clock|negedge reset) begin

if (reset) begin

store <= 32'd0;
end else begin

store <= a;
end
end
b = store;
endmodule

