/*
   Automatically generated by the Phi Compiler 0.0.1-dev (caef566)
   Do not modify.
   Generated on: 2018-10-28 10:58:56
*/

module dFlipFlop(
    input [64'd31:64'd0] a,
    output [64'd31:64'd0] b,
    input  clock,
    input reset
);

reg [64'd31:64'd0] store;
always @ (posedge clock|negedge reset) begin // Cannot change to or as Verilog demands.

if (reset) begin

store <= 32'd0;
end else begin

store <= a;
end
end
b = store; // Cannot add assign here due to noncontextual translation.
endmodule

